name: frontend CI/CD

on:
  push:
    branches: [ "develop" ]

jobs:

  redeploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Development/frontend
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies, build
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: './Development/frontend/package-lock.json'
    - run: npm ci
    - run: npm run build

    - name: Copy build folder via scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "Development/frontend/build"
        target: "frontend"

    - name: Update virtualhost root dir with new build
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: ~/cb
